# This is a basic workflow to help you get started with Actions

name: Create Release Testing

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Create release
        uses: ./
        with:
          tag_name: v1.0.0
          name: Release v1.0.0
          body: |
            Init action
          draft: false
          prerelease: true
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
